/* Generates core/vectors.json from babel-core.mjs -- the shared ground
 * truth for every consumer. Deterministic: the sample cells come from a
 * fixed integer walk, not a random source, so the file only changes when
 * the core's behaviour does. Regenerate deliberately, never to make a
 * failing test pass. */

import { writeFileSync } from "node:fs";
import * as core from "./babel-core.mjs";
import * as text from "./babel-text.mjs";

/* A fixed spread of cells: some near the origin, some far, plus the
   crimson volume's own gallery and a few cells of each type. */
function sampleCells(n){
  const out = [];
  let q = 0, r = 0, fl = 0;
  for (let k = 0; k < n; k++){
    out.push({ q, r, floor: fl });
    /* a deterministic scatter, wide enough to leave the origin's basin */
    const h = core.uhash(core.u32(k * 0x9E3779B9));
    q += ((h & 0xFF) - 128);
    r += (((h >>> 8) & 0xFF) - 128);
    fl = (((h >>> 16) & 7) - 3);
  }
  return out;
}

const cells = [
  { q: core.CRIM.q, r: core.CRIM.r, floor: core.CRIM.floor },
  ...sampleCells(120)
];

const topology = cells.map(c => ({
  ...c,
  type: core.cellType(c.q, c.r),
  gaps: [0,1,2,3,4,5].map(i => core.gapAt(c.q, c.r, i, c.floor)),
  axis: core.axisOf(c.q, c.r),
  rise: core.riseOf(c.q, c.r),
  studyKeyMod8: core.studyKey(c.q, c.r, c.floor) % 8,
  studyKit: core.studyKit(core.studyKey(c.q, c.r, c.floor)),
  studyAnchor: core.cellType(c.q, c.r) === core.TYPE.STUDY
    ? core.studyAnchor(c.q, c.r, c.floor, core.studyKey(c.q, c.r, c.floor)) : -1,
  shelvedWalls: core.shelvedWalls(c.q, c.r, c.floor),
  cellKey: core.cellKey(c.q, c.r),
  edgeKeys: [0,1,2,3,4,5].map(i => core.edgeKey(c.q, c.r, i, c.floor))
}));

/* Content vectors: a handful of addresses, with symbols at positions
   chosen to cover the first page, a page boundary, and the last symbol. */
const POSITIONS = [0, 1, 79, 80, 3199, 3200, 655999, 1311999];
const addresses = [
  text.walkAddress({ q: core.CRIM.q, r: core.CRIM.r, floor: core.CRIM.floor,
                     wall: core.CRIM.wall, shelf: core.CRIM.shelf, slot: core.CRIM.slot }),
  text.walkAddress({ q: 0, r: 0, floor: 0, wall: 0, shelf: 0, slot: 0 }),
  text.walkAddress({ q: 0, r: 0, floor: 0, wall: 0, shelf: 0, slot: 1 }),
  text.walkAddress({ q: -7, r: 12, floor: -2, wall: 3, shelf: 4, slot: 34 }),
  text.textAddress({ phrase: "axaxaxas mlo", offset: 0 }),
  text.textAddress({ phrase: "the library is unlimited and cyclical.", offset: 12345 })
];

const content = addresses.map(a => ({
  uri: text.formatAddress(a),
  spine: text.spineLabel(a),
  symbols: POSITIONS.map(p => ({ p, s: text.symbolAt(a, p) })),
  page0Line0: text.lineOf(a, 0, 0),
  page409Line39: text.lineOf(a, 409, 39)
}));

const vectors = {
  note: "Generated by core/gen-vectors.mjs. Shared ground truth for the JS core, "
      + "the GLSL port (core/conformance.html) and the agent skill. Do not hand-edit.",
  alphabet: text.ALPHABET,
  C: text.C, pages: text.PAGES, lines: text.LINES, cols: text.COLS,
  probabilities: { P_OPEN: core.P_OPEN, P_SHAFT: core.P_SHAFT,
                   P_STAIR: core.P_STAIR, P_STUDY: core.P_STUDY },
  topology, content
};

writeFileSync(new URL("./vectors.json", import.meta.url),
              JSON.stringify(vectors, null, 1) + "\n");
console.log(`wrote vectors.json: ${topology.length} cells, ${content.length} addresses`);
